import = ["/home/bieniucieniu/.alacritty-colorscheme/themes/campbell.yaml"]

[env]
TERM = "xterm-256color"

[font]
size = 11.5

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window.padding]
x = 0
y = 0
